### ISSUE TITLE
How many data of Mixamo did you use for training?

### ISSUE THREAD

**Issue by ANYMS-A** [DetectiveLYJ/Pose-Retargeting-using-CycleGAN-#1]
Hi, 

I was recently reproducing the work of Skeleton motion retargeting(https://github.com/crissallan/Skeleton_Aware_Networks_for_Deep_Motion_Retargeting). 

But I met a problem which is the lacking of data, I couldn't test the generalization ability of the model.

So I'd like to know are there any way to download the animation files of "Mixamo" efficiently? Like web scrawler or something.

Many thanks!

**Comment by DetectiveLYJ** [comment]
You can try to download ‘Mixamo’ datasets with this [script](https://forums.unrealengine.com/community/community-content-tools-and-tutorials/1376068-script-mixamo-download-script).

This code is for pose retargeting(not motion retargeting),  you need about 1000 frames of poses for every character to train.
And this method can only retarget between two characters.

if you want to do motion retargeting, you can reference the [2D motion retargeting](https://github.com/ChrisWu1997/2D-Motion-Retargeting) work.

And if you use the 3D skeletons, you can change the number of channels of the network and retrain a new model.

**Comment by DetectiveLYJ** [comment]
我在github上回你啦，对啦，你也是做retargeting相关的研究吗？我是之前一直在做姿态重定向的项目，对motion retargeting也有一些了解，如果方便的话我们加个微信吧，以后有什么发现也可以交流一下，我微信号是：15817212819，昵称：贝尔摩劼





---Original---
